import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/dropzone/styles.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Box, ColorSchemeScript } from "@mantine/core";
import { SupabaseWrapper } from "@/providers/SupabaseWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BirdBase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <SupabaseWrapper>
          <Box bg="gray.0" mih="100dvh" h={0}>
            {children}
          </Box>
        </SupabaseWrapper>
      </body>
    </html>
  );
}
